spring:
  jackson:
    serialization: {indent-output: true}
  sleuth:
    sampler: {probability: 1}
  mail: {port: 25, host: localhost}
  zipkin:
    base-url: http://localhost:9411
    locator:
      discovery: {enabled: true}
    enabled: false
  couchbase:
    bucket: {password: password@1234, name: default}
    bootstrap-hosts: couchbase-example.mergedemo-dev
  profiles:
    include: [swagger]
    active: dev
  messages: {cache-duration: PT1S}
  jpa:
    properties: {hibernate.cache.hazelcast.instance_name: mergedemosvc}
  main: {allow-bean-definition-overriding: true}
  devtools:
    livereload: {enabled: false}
    restart: {enabled: true}
  thymeleaf: {cache: false}
server: {port: 8080}
jhipster:
  cache:
    hazelcast:
      management-center: {update-interval: 3, enabled: false, url: 'http://localhost:8180/mancenter'}
      time-to-live-seconds: 3600
      backup-count: 1
  security:
    authentication:
      jwt: {base64-secret: MjA5NzNkNTE4MTQyYzllYWY3OTM2ZDg2YTU3ZGE2ZGY5NGJkZTNkOWQ3OGU5OTgxZjFmODEyY2Q1OWIxODJiNmI4NDQ3YTc1YzY4MDYwODZjMjU3NWU3ZDJlOTE4ZGQ2ZDhkOTdkNmRjYjIyYmJhOTE4MTRiNTU1MTE2NDE1OWQ=,
        token-validity-in-seconds: 86400, token-validity-in-seconds-for-remember-me: 2592000}
  mail: {base-url: 'http://127.0.0.1:8080', from: mergedemosvc@localhost}
  clientApp: {name: mergedemosvc}
  logging:
    logstash: {port: 5000, queue-size: 512, host: localhost, enabled: false}
    use-json-format: false
  metrics:
    logs: {report-frequency: 60, enabled: false}
management:
  endpoint:
    jhi-metrics: {enabled: true}
    health: {show-details: when-authorized}
    prometheus: {enabled: true}
  endpoints:
    web:
      exposure: {include: 'configprops,env,health,info,threaddump,logfile,jhi-metrics,prometheus'}
logging:
  level: {ROOT: DEBUG, com.infy.mergedemosvc: DEBUG, io.github.jhipster: DEBUG}
